import './global.css';
import { ThemeProvider } from '@shared/ui-shared';

export const metadata = {
  title: 'Welcome to finance-dashboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar">
      <body>
        <ThemeProvider lang="ar">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
