export const CURRENCIES = {
  USD: 'USD',
  EUR: 'EUR',
  GBP: 'GBP',
  JPY: 'JPY',
  CAN: 'CAD',
  UK: 'GBP',
  JAP: 'JPY',
  KOR: 'KRW',
  CHN: 'CNY',
  IND: 'INR',
  BRA: 'BRL',
  MEX: 'MXN',
  ARG: 'ARS',
  AED: 'AED',
  SAU: 'SAR',
  KWT: 'KWD',
  QAT: 'QAR',
  BHR: 'BHD',
  OMR: 'OMR',
  KEN: 'KES',
  NGA: 'NGN',
  ZAF: 'ZAR',
  ZMB: 'ZMW',
};